AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Get User Permissions

  Sample SAM Template for node-deployment

Parameters:
  ApiId:
    Description: Api Id
    Type: String
    Default: pjdf9a93ye


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  insertNewTrafficModel:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "getUserPermissions"
      Description: "Get User permissions" 
      CodeUri: getUserPermissions/index.js
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      "Role" : { "Fn::Sub" : "arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role" }
      Architectures:
        - x86_64
      Environment:
        Variables:
        Variables:
          DATABASE: "electrotempo"  
          SCHEMA: "et_auth" 
          DB_CREDENTIALS_SECRET_NAME: "postgres_user_auth_manager"         
      VpcConfig:
        SubnetIds:
          - subnet-aa9d48c1
          - subnet-ca0a09b0
          - subnet-e18be0ad
        SecurityGroupIds:
          - sg-8516f0f9
      Layers:
          - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:electrotempo-auth:3"
          - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:serverless-postgres:3"

  insertNewTrafficModelPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::GetAtt:
        - insertNewTrafficModel
        - Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/GET/user-permissions"

     
 

