version: "3.8"

services:
  database:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    command: -p 5432
