export const growthScenarioSimulationParameters = [
  {
    //id: 1,
    ev_growth_scenario_id: 1,
    vehicle_class_id: 3,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 2,
    ev_growth_scenario_id: 2,
    vehicle_class_id: 3,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 3,
    ev_growth_scenario_id: 3,
    vehicle_class_id: 3,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 4,
    ev_growth_scenario_id: 4,
    vehicle_class_id: 3,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 5,
    ev_growth_scenario_id: 1,
    vehicle_class_id: 4,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 6,
    ev_growth_scenario_id: 2,
    vehicle_class_id: 4,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 7,
    ev_growth_scenario_id: 3,
    vehicle_class_id: 4,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 8,
    ev_growth_scenario_id: 4,
    vehicle_class_id: 4,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 9,
    ev_growth_scenario_id: 5,
    vehicle_class_id: 3,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
  {
    //id: 10,
    ev_growth_scenario_id: 6,
    vehicle_class_id: 4,
    initial_num_vehicles: 1000000,
    ev_retrofit_rate: 0,
    vehicle_population_growth_rate: 0.0017,
    scrappage_incentive_size_frac: 0,
    target_year_market_share_frac: 0.5,
    target_year: 2030,
    current_market_share_frac: 0.05,
    final_market_share_frac: 1,
    final_year: 2060,
    scrappage_incentive_program: false,
    ev_retrofit_incentive_program: false,
    current_year: 2022,
    start_year: 2010,
    start_year_market_share_frac: 0,
    scrappage_rate: 0,
    ev_retrofit_incentive_size_frac: 0,
    inserted_by: "seed",
  },
]
