export const trafficModel = [
  {
    id: 1,
    name: "Houston 8 County Variant",
    description: "Houston 8 County Variant",
    model_year: 2020,
    location_id: 1,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 2,
    name: "TxPPC",
    description: "TxPPC Variant",
    model_year: 2022,
    location_id: 76,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 3,
    name: "CPS",
    description: "CPS Variant",
    model_year: 2022,
    location_id: 79,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 4,
    name: "LCRA",
    description: "LCRA Variant",
    model_year: 2022,
    location_id: 81,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 5,
    name: "NBU",
    description: "NBU Variant",
    model_year: 2022,
    location_id: 80,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 6,
    name: "Austin Energy",
    description: "Austin Energy Variant",
    model_year: 2015,
    location_id: 78,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
  {
    id: 7,
    name: "First Energy",
    description: "First Energy Variant",
    model_year: 2022,
    location_id: 82,
    num_vehicles: 1000000,
    model_type: "MPO",
    inserted_by: "seed",
  },
];
