export const utilityRates = [
  {
    utilityId: 1,
    name: "Dominion Energy Standard",
    organizationId: 37,
    peakDemandChargePricePerKw: 8.03,
    ppaPeakDemandChargePricePerKw: 5,
    distributionDemandChargePricePerKw: 1.15,
    ppaGenerationChargePricePerKwh: 0.02,
    generationChargePricePerKwh: 0.05,
    distributionChargePricePerKwh: 0.4,
    transmissionChargePricePerKwh: 0.004886,
    transmissionUsageKwh: 0,
    totalUsageKwh: 3930110,
    generationDemandChargePricePerKw: 0.05,
    transmissionDemandChargePricePerKw: 0.004886,
    ppaTransmissionChargePricePerKwh: 0.004886,
    ppaDistributionChargePricePerKwh: 1.15,
    ppaGenerationDemandChargePricePerKw: 0.02,
    ppaTransmissionDemandChargePricePerKw: 0.004886,
    ppaDistributionDemandChargePricePerKw: 1.15,
  },
  {
    utilityId: 1,
    name: "Dominion Energy v2",
    organizationId: 37,
    peakDemandChargePricePerKw: 9.18,
    ppaPeakDemandChargePricePerKw: 4,
    distributionDemandChargePricePerKw: 0.8,
    ppaGenerationChargePricePerKwh: 0.02,
    generationChargePricePerKwh: 0.05,
    distributionChargePricePerKwh: 0.4,
    transmissionChargePricePerKwh: 0.004886,
    transmissionUsageKwh: 0,
    totalUsageKwh: 2975000,
    generationDemandChargePricePerKw: 0.05,
    transmissionDemandChargePricePerKw: 0.004886,
    ppaTransmissionChargePricePerKwh: 0.004886,
    ppaDistributionChargePricePerKwh: 0.8,
    ppaGenerationDemandChargePricePerKw: 0.02,
    ppaTransmissionDemandChargePricePerKw: 0.004886,
    ppaDistributionDemandChargePricePerKw: 0.8,
  },
];
