AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Get Traffic Model Download URL

  Sample SAM Template for node-deployment

Parameters:
  ApiId:
    Description: Api Id
    Type: String
    Default: aq93d0b8v9


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  getTrafficModelDownloadURL:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "getTrafficModelDownloadURL"
      Description: "Get Traffic Model Download URL" 
      CodeUri: getTrafficModelDownloadURL/index.js
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      "Role" : { "Fn::Sub" : "arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role" }
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_BUCKET: "et-tti-customer-traffic-model-prod"  

  getTrafficModelDownloadURLPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::GetAtt:
        - getTrafficModelDownloadURL
        - Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/GET/traffic-model/download"

     
 

