export const terminalScenarios = [
  {
    propertyId: 1,
    facilityId: 1,
    name: "Terminal 1 Scenario 1",
    planningHorizonYears: 12,
    numChargers: 10,
    chargerId: 1,
    optNumChargers: 8,
    active: true,
    utilityRateId: 1,
    chargerReplacementLifecycleYears: 12,
  },
  {
    propertyId: 1,
    facilityId: 1,
    name: "Terminal 1 Scenario 2",
    planningHorizonYears: 9,
    numChargers: 12,
    chargerId: 1,
    optNumChargers: 10,
    active: true,
    utilityRateId: 1,
    chargerReplacementLifecycleYears: 12,
  },
  {
    propertyId: 1,
    facilityId: 1,
    name: "Hybrid Scenario",
    planningHorizonYears: 12,
    numChargers: 24,
    chargerId: 1,
    optNumChargers: 30,
    active: true,
    utilityRateId: 1,
    chargerReplacementLifecycleYears: 12,
  },
];
