export const terminalScenarioVehicles = [
  {
    scenarioId: 1,
    vehicleTypeId: 1,
    iceVehicleId: 3,
    evVehicleId: 1,
    fleetSize: 16,
    vehiclesPerShift: 8,
    numICEVehicles: 20,
    numICEVehiclesToElectrify: 20,
    vehicleReplacementLifecycleYears: 12,
    batteryReplacementLifecycleYears: 6,
    iceFuelConsumption: 1,
    shiftSchedule: [
      1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
    ],
  },
  {
    scenarioId: 2,
    vehicleTypeId: 2,
    iceVehicleId: 4,
    evVehicleId: 2,
    fleetSize: 20,
    vehiclesPerShift: 12,
    numICEVehicles: 30,
    numICEVehiclesToElectrify: 30,
    vehicleReplacementLifecycleYears: 12,
    batteryReplacementLifecycleYears: 6,
    iceFuelConsumption: 4,
    shiftSchedule: [
      2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1,
    ],
  },
  {
    scenarioId: 3,
    vehicleTypeId: 1,
    iceVehicleId: 5,
    evVehicleId: 1,
    fleetSize: 16,
    vehiclesPerShift: 8,
    numICEVehicles: 20,
    numICEVehiclesToElectrify: 20,
    vehicleReplacementLifecycleYears: 12,
    batteryReplacementLifecycleYears: 6,
    iceFuelConsumption: 1,
    shiftSchedule: [
      1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
    ],
  },
];
